version: 2
jobs:
  build:
    docker:
      - image: team5499/frc-testing-image:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Prepare the test environment
          command: |
            git config --global user.email '<>'
            git config --global user.name 'CircleCI User'
      - run:
          name: Run tests
          command: |
            ./test.sh
