repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: mixed-line-ending
    -   id: pretty-format-json
        args: [--autofix]
    - id: trailing-whitespace
